name: bookia_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_luancher_icons:
  image_path: "assets/icons/book.png"
  android: true
  ios: true

flutter:
  fonts:
    - family: DM Serif Display
      fonts: 
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
        - asset: assets/fonts/DMSerifDisplay-Italic.ttf
          style: italic 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
